{
 "title": "{{ wpsite }}",
 "tags": [ "website" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status / String Search",
   "type": "stat",
   "description": "Monitoring of the HTTP Response - LAST STATE\n",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HTTP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"http_response_code\") FROM \"http_response\" WHERE (\"server\" =~ /{{ wpsite }}/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$fqdn$/" }
     ]
    },
    {
     "alias": "Search",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"response_string_match\") FROM \"http_response\" WHERE (\"server\" =~ /{{ wpsite }}/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "response_string_match" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$fqdn$/" }
     ]
    }
   ]
  },
  {
   "title": "Alert graph for HTTP status",
   "type": "graph",
   "description": "Monitoring of the HTTP Response - ALERT GRAPH FOR HTTP RESPONSE",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"http_response_code\") FROM \"http_response\" WHERE (\"server\" =~ /{{ wpsite }}/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://{{ wpsite }}/" }
     ]
    }
   ]
  },
  {
   "title": "Links",
   "type": "text",
   "description": "HTML Widget with useful links",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 0 },
   "options": {
    "content": "<p>Put useful links and info here</p>    "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Response in ms",
   "type": "graph",
   "description": "Response times measured by remote telegraf agent",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"response_time\") FROM \"http_response\" WHERE (\"server\" = 'https://{{ wpsite }}/') AND $timeFilter GROUP BY time($__interval), \"server\" fill(none)",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://{{ wpsite }}/" }
     ]
    }
   ]
  },
  {
   "title": "Alert graph for string search",
   "type": "graph",
   "description": "Monitoring of the HTTP Response - ALERT GRAPH FOR SEARCH STRING",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "String found",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "SELECT last(\"response_string_match\") FROM \"http_response\" WHERE (\"server\" =~ /$url/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "response_string_match" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "https://{{ wpsite }}/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "graph",
   "description": "Bytes measured from webserver access_log",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Bytes/minute",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "virtualhost" ], "type": "tag" }
     ],
     "measurement": "access_log",
     "query": "SELECT sum(\"resp_bytes\") FROM \"access_log\" WHERE (\"virtualhost\" = '{{ wpsite }}') AND $timeFilter GROUP BY time(1m), \"virtualhost\"",
     "select": [
      [
       { "params": [ "resp_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "virtualhost", "operator": "=", "value": "{{ wpsite }}" }
     ]
    }
   ]
  },
  {
   "title": "access log hits",
   "type": "graph",
   "description": "Access log hit count per fixed time interval",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Entries/minute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "access_log",
     "query": "SELECT count(\"request\") FROM \"access_log\" WHERE (\"virtualhost\" = '{{ wpsite }}') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "request" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "virtualhost", "operator": "=", "value": "$fqdn" }
     ]
    }
   ]
  },
  {
   "title": "error log hits",
   "type": "graph",
   "description": "Error log hit count per fixed time interval",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Entries/minute",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "error_log",
     "query": "SELECT count(\"message\") FROM \"error_log\" WHERE (\"path\" = '/var/log/{{ servertype }}/{{ wpsite }}-error.log') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  }
 ]
}